### ISSUE TITLE
No support for percentages

### ISSUE THREAD

**Issue by kim3er** [agworld/soroban#4]
To use the example given in the README:

This works:

```
s.C1 = "=A1-10"
```

This doesn't:

```
s.C1 = "=A1-10%"
```

Error:

```
Soroban::ParseError: Expected one of ., ^, *, /, +, -, =, <>, >=, <=, >, <, and, or at line 1, column 7 (byte 7) after
    from /path/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/soroban-0.9.1/lib/soroban/cell.rb:43:in `set'
```

I'm importing a spreadsheet.

**Comment by kim3er** [comment]
The problem with percentages is that they're relative to the value on the other side of the formula.

Is it possible to convert `A1 + 10%` to something like `A1 + ( A1 * 0.1 )`?

**Comment by kranzky** [comment]
Are you sure that's what it does? In Google Sheets `+ 10%` is equivalent to `+ 0.1`

**Comment by kim3er** [comment]
Of course, looking too closely at the screen I think. That would do the job exactly. Can this be achieved through treetop grammars?

**Comment by kim3er** [comment]
@jasonhutchens Thanks again for your quick turn around. Can I ask, is the `grammar.rb` auto generated, and if so, how?

**Comment by kranzky** [comment]
You generate `grammar.rb` by running `bundle exec rake treetop`.
